### ISSUE TITLE
Remove encrypted passwords from repository

### ISSUE THREAD

**Issue by larsks** [CCI-MOC/ansible-switches#4]
I'm not a huge fan of including encrypted data in the repository, particularly when using a single shared key. There are several problems with this arrangement:

- If the key is ever compromised, that means that any encrypted data in your git history is compromised forever. Even if you change the key, existing data can always be decrypted by anyone with the compromised key and the git history.
- It's very difficult to work on the repository: even in cases in which the encrypted data isn't necessary, it's not possible to run even trivial playbooks for testing because Ansible will error out due to the missing key.
- The vault key provides all-or-nothing access: there's not way to restrict someone's access to only certain passwords.

I would prefer to remove the encrypted passwords from the repository and place them in a key store that can be accessed using Ansible lookup plugins (we've used [AWS SecretsManager][] for this in the past, and there appears to be support for [Bitwarden][] as well). Using a lookup plugin means that credentials are only necessary when something requires one of the secrets (so it's possible to run test playbooks and such that don't actually interact with the switches), and we're no longer relying on a single shared key to access the secrets -- everyone who needs access has their own credentials, and access to the keys can be managed centrally.

[bitwarden]: https://docs.ansible.com/ansible/latest/collections/community/general/bitwarden_lookup.html
[aws secretsmanager]: https://docs.ansible.com/ansible/latest/collections/amazon/aws/aws_secret_lookup.html

**Comment by hakasapl** [comment]
Agreed, I will look into using AWS SecretsManager
